"""Smoke + correctness tests for piDMD and KernelDMD."""

import numpy as np
import pytest
import sys, pathlib

sys.path.insert(0, str(pathlib.Path(__file__).parent.parent))

import dmd_toolkit as dmd
from dmd_toolkit.pidmd import CONSTRAINTS


def _clean_oscillator():
    return dmd.data.two_mode_oscillator(nx=80, nt=200, dt=0.05, noise=0.0)


# --------------------------------------------------------------------------
# piDMD
# --------------------------------------------------------------------------
def test_pidmd_unitary_recovers_freqs():
    X, _, t = _clean_oscillator()
    m = dmd.pidmd(X, constraint="unitary", rank=2, dt=0.05)
    freqs = np.sort(np.abs(m.frequencies))
    # Unitary constraint zeros out the decay rate, but freqs should be close
    assert np.any(np.abs(freqs - 1.0) < 0.2), f"expected ~1Hz; got {freqs}"
    assert np.any(np.abs(freqs - 5.5) < 0.2), f"expected ~5.5Hz; got {freqs}"


def test_pidmd_unitary_is_orthogonal():
    X, _, _ = _clean_oscillator()
    m = dmd.pidmd(X, constraint="unitary", rank=4, dt=0.05)
    err = np.linalg.norm(m.A.conj().T @ m.A - np.eye(m.A.shape[0]))
    assert err < 1e-8, f"Q not orthogonal: ||Q^*Q - I|| = {err:.3e}"
    # All eigenvalues should have unit modulus
    assert np.all(np.abs(np.abs(m.eigenvalues) - 1.0) < 1e-6)


def test_pidmd_symmetric_is_hermitian():
    X, _, _ = _clean_oscillator()
    m = dmd.pidmd(X, constraint="symmetric", rank=4, dt=0.05)
    err = np.linalg.norm(m.A - m.A.conj().T)
    assert err < 1e-6, f"A not Hermitian: ||A - A^*|| = {err:.3e}"
    # Hermitian matrix has real eigenvalues
    assert np.all(np.abs(np.imag(m.eigenvalues)) < 1e-6)


def test_pidmd_skew_recovers_skew_dynamics():
    """Generate snapshots from a skew-Hermitian generator and check piDMD
    with the skew_symmetric constraint recovers it. (The two-oscillator
    fixture is not generated by a skew operator, so we use a tailored one.)
    """
    rng = np.random.default_rng(0)
    n, T, dt = 5, 200, 0.05
    Araw = rng.standard_normal((n, n)) + 1j * rng.standard_normal((n, n))
    S = (Araw - Araw.conj().T) / 2  # skew-Hermitian generator
    # Discrete-time evolution: x_{k+1} = exp(S * dt) x_k. exp(skew) is unitary,
    # so iteration stays bounded.
    from scipy.linalg import expm
    M = expm(S * dt)
    x0 = rng.standard_normal(n) + 1j * rng.standard_normal(n)
    X = np.empty((n, T), dtype=complex)
    X[:, 0] = x0
    for k in range(1, T):
        X[:, k] = M @ X[:, k - 1]
    m = dmd.pidmd(X, constraint="skew_symmetric", rank=n, dt=dt)
    err = np.linalg.norm(m.A + m.A.conj().T)
    assert err < 1e-6, f"A not skew: ||A + A^*|| = {err:.3e}"


def test_pidmd_diagonal_reconstructs_separable():
    # Channels evolve independently: each row is its own complex exponential
    nf, nt, dt = 6, 200, 0.05
    t = np.arange(nt) * dt
    lambdas = np.exp((0.0 + 2j * np.pi * np.array([0.2, 0.5, 1.0, 1.7, 2.3, 3.1])) * dt)
    X = np.empty((nf, nt), dtype=complex)
    for i in range(nf):
        X[i] = lambdas[i] ** np.arange(nt)
    m = dmd.pidmd(X, constraint="diagonal", dt=dt)
    # Diagonal A's diagonal should be the per-row eigenvalues
    assert np.allclose(np.diag(m.A), lambdas, atol=1e-8)
    rec = m.reconstruct(t)
    rel = np.linalg.norm(rec - X, "fro") / np.linalg.norm(X, "fro")
    assert rel < 1e-8, f"Diagonal piDMD reconstruction error {rel:.3e}"


def test_pidmd_circulant_diagonal_in_fourier():
    # Build data from a known circulant generator: shift + diagonal decay
    rng = np.random.default_rng(0)
    n, T = 16, 200
    # Random circulant via DFT-domain diagonal eigenvalues on unit circle
    a_hat = np.exp(1j * 2 * np.pi * np.fft.fftfreq(n))
    F = np.fft.fft(np.eye(n), axis=0)
    Finv = F.conj().T / n
    C = Finv @ np.diag(a_hat) @ F
    x = rng.standard_normal(n) + 1j * rng.standard_normal(n)
    X = np.empty((n, T), dtype=complex)
    X[:, 0] = x
    for k in range(1, T):
        X[:, k] = C @ X[:, k - 1]
    m = dmd.pidmd(X, constraint="circulant", dt=1.0)
    # Recovered DFT-domain eigenvalues should match a_hat (up to ordering)
    assert np.allclose(np.sort(np.abs(m.eigenvalues - a_hat)), 0, atol=1e-8)


def test_pidmd_constraint_list_complete():
    # Sanity: the exported tuple matches the dispatch
    expected = {"unitary", "symmetric", "skew_symmetric", "diagonal", "circulant"}
    assert set(CONSTRAINTS) == expected


# --------------------------------------------------------------------------
# KernelDMD
# --------------------------------------------------------------------------
def test_kernel_dmd_linear_produces_valid_spectrum():
    """Linear kernel gives a well-defined spectrum on real data (Lorenz).
    The linear kernel can't fit chaotic dynamics, but eigenvalues must be
    finite and shapes correct.
    """
    X, t = dmd.data.lorenz(n_steps=300, dt=0.01)
    k = dmd.kernel_dmd(X, kernel="linear", rank=3, dt=0.01)
    assert k.eigenvalues.shape[0] == 3
    assert np.all(np.isfinite(np.abs(k.eigenvalues)))
    assert k.modes.shape == (3, 3)


def test_kernel_dmd_rbf_reconstructs_lorenz():
    """RBF kernel DMD should reconstruct the training portion of Lorenz
    significantly better than chance (normalised error well below 1).
    """
    X, t = dmd.data.lorenz(n_steps=300, dt=0.01)
    k = dmd.kernel_dmd(X, kernel="rbf", rank=20, dt=0.01)
    rec = k.reconstruct(t)
    rel = np.linalg.norm(rec - X, "fro") / np.linalg.norm(X, "fro")
    assert rel < 0.5, f"RBF kernel DMD reconstruction error {rel:.3e}"


def test_kernel_dmd_eigenfunctions_on_train_match_attribute():
    X, t = dmd.data.lorenz(n_steps=300, dt=0.01)
    k = dmd.kernel_dmd(X, kernel="rbf", rank=8, dt=0.01)
    phi_train_recomputed = k.eigenfunctions(X[:, :-1])
    assert phi_train_recomputed.shape == k.eigenfunctions_train.shape
    assert np.allclose(phi_train_recomputed, k.eigenfunctions_train, atol=1e-8)


def test_kernel_dmd_polynomial():
    X, t = dmd.data.lorenz(n_steps=300, dt=0.01)
    k = dmd.kernel_dmd(X, kernel="poly", rank=6, dt=0.01, degree=2, coef0=1.0)
    assert k.eigenvalues.shape[0] == 6
    rec = k.reconstruct(t)
    assert rec.shape == X.shape


def test_kernel_dmd_rank_fraction():
    X, t = dmd.data.lorenz(n_steps=300, dt=0.01)
    k = dmd.kernel_dmd(X, kernel="rbf", rank=0.99, dt=0.01)
    assert k.eigenvalues.shape[0] >= 1
